### ISSUE TITLE
first time iterating over arrays

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/wwdc-badges#4]
This lab is the first time we are asking students to iterate over an array and I found that the previous `for` loop reading didn't give me a good example of how to do that––only how to iterate over a string. I was able to look it up without too much difficulty but the idea is that we want to keep students in the Learn universe as much as possible. I think this could be solved with another `for` example of iterating over arrays, maybe in array readme and/or add array example and test in a simple lab prior to this one. 

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing for now. @markedwardmurray  close when you're done with the issue.

**Comment by markedwardmurray** [comment]
resolves by objc-fizzbuzz https://github.com/learn-co-curriculum/objc-fizzbuzz
