### ISSUE TITLE
This readme references OO and classes, but they haven't been discussed yet.

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/wwdc-badges#5]
We haven’t talked about classes yet, but they're referenced in this readme a lot. Are we assuming knowledge of OO before this?

**Comment by markedwardmurray** [comment]
did you mean to open this issue on https://github.com/learn-co-curriculum/wwdc-badges-methods ?

**Comment by dfenjves** [comment]
Meant to open on tests readme! Sorry!
