### ISSUE TITLE
The @implementation and @end haven’t been explained yet

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/wwdc-badges#6]
"The SpecBegin(<className>) and SpecEnd are wrappers similar to the@implementation and @end in the FISAppDelegate.m file and the compiler will complain if these are interrupted or missing." -> this is the first time I hear about @implementation and @end, so may be confusing.

**Comment by markedwardmurray** [comment]
did you mean to open this on https://github.com/learn-co-curriculum/reading-ios-using-tests ?

**Comment by dfenjves** [comment]
Oops! Meant to open on methods readme!
